In [2]:
import pandas as pd
import numpy as np
# Set random seed for reproducibility
np.random.seed(42)
# Generate 1000 rows with 4 columns
n_rows = 1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10, 500, n_rows)
}
df = pd.DataFrame(data)

# Display first few rows
print(df.head())
print(f"\nDataset shape: {df.shape}")

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

Dataset shape: (1000, 4)


In [3]:
df.head()

,color,size,material,price
0,green,large,metal,423
1,red,large,plastic,351
2,green,large,plastic,229
3,green,large,wood,400
4,red,small,plastic,172


In [4]:
# pip install category_encoders

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [6]:
X = df.drop(columns='price')
y= df.price
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

In [7]:
label_encoder = LabelEncoder()
''' 
# updated_xtrain = label_encoder.fit_transform(xtrain)
ValueError: y should be a 1d array, 
got an array of shape (800, 3) instead.

'''

' \n# updated_xtrain = label_encoder.fit_transform(xtrain)\nValueError: y should be a 1d array, \ngot an array of shape (800, 3) instead.\n\n'

In [8]:
label_encoder.fit_transform(xtrain['color'])     #accepts only 1 col

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2,

In [9]:
# label_encoder.transform(xtest)       
'''y should be a 1d array, 
got an array of shape (200, 3) instead.
'''

'y should be a 1d array, \ngot an array of shape (200, 3) instead.\n'

In [10]:
#new input(unseen data)
new_input=['red','red']         
'''all value present then we will transform the values 
- NOT handle unknown labels(label encoder)'''
label_encoder.transform(new_input)

array([2, 2])

In [11]:
#One hot encoder
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)   #sparse_output=False   directly get array
updated_xtrain=encoder.fit_transform(xtrain)             #create new unique columns  shape (800, 9)  #NOT possible to pass 1 col like color only in fit transform
updated_xtrain


array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [12]:
#One hot encoder 2nd method using 2 array


# from sklearn.preprocessing import OneHotEncoder
# encoder=OneHotEncoder()   #sparse_output=True(default)
# values=encoder.fit_transform(xtrain)             #create new unique columns  shape (800, 9)  #not possible to pass 1col like color only in fit transform
# # toarray()
# values=values.toarray()






In [13]:
xtrain       #800 rows × 3 columns

,color,size,material
29,green,small,wood
535,blue,medium,metal
695,blue,small,wood
557,red,small,plastic
836,green,large,plastic
...,...,...,...
106,red,large,plastic
270,red,small,plastic
860,blue,large,plastic
435,blue,small,plastic


In [14]:
columns=encoder.get_feature_names_out()       # return column names based on aescending order

In [15]:
columns

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

In [16]:
# values

In [17]:
# pd.DataFrame(values,columns=columns).astype(int)

In [18]:
encoder.transform(xtest[['color','size','material']])    #or             encoder.transform(xtest)
# fit transform and transform have same col ,The feature names should match those that were passed during fit


encoder.transform(xtest)  #valid syntax why? x test is 2-D 

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [19]:
# # new_input=[['red'],['large']]   #invalid syntax
# new_input=[['red','large'],['blue','small']]

# encoder.transform(new_input)   
# '''ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.'''


In [20]:
# new_input=[['red','large','plastic'],['blue','smaller','wood']]   
'''ValueError: Found unknown categories ['smaller'] 
in column 1 during transform
'''
encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')          #default unknown value -- error
new_input=[['red','large','plastic'],['blue','smaller1','wood1']]      #ignore is used to ignore unknown values (assigns-> 0., 0., 0.)
encoder.fit_transform(xtrain)
encoder.transform(new_input)   

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
col=encoder.get_feature_names_out()

In [22]:
updated_xtrain

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [24]:
pd.DataFrame(updated_xtrain,columns=col).astype(int)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0,1,0,0,0,1,0,0,1
1,1,0,0,0,1,0,1,0,0
2,1,0,0,0,0,1,0,0,1
3,0,0,1,0,0,1,0,1,0
4,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
795,0,0,1,1,0,0,0,1,0
796,0,0,1,0,0,1,0,1,0
797,1,0,0,1,0,0,0,1,0
798,1,0,0,0,0,1,0,1,0
