In [118]:
import pandas as pd
import numpy as np
# Set random seed for reproducibility
np.random.seed(42)
# Generate 1000 rows with 4 columns
n_rows = 1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10, 500, n_rows)
}
df = pd.DataFrame(data)

# Display first few rows
print(df.head())
print(f"\nDataset shape: {df.shape}")

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

Dataset shape: (1000, 4)


In [119]:
df.head()

,color,size,material,price
0,green,large,metal,423
1,red,large,plastic,351
2,green,large,plastic,229
3,green,large,wood,400
4,red,small,plastic,172


In [120]:
# pip install category_encoders

In [121]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [122]:
X = df.drop(columns='price')
y= df.price
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

In [123]:
label_encoder = LabelEncoder()
''' 
# updated_xtrain = label_encoder.fit_transform(xtrain)
ValueError: y should be a 1d array, 
got an array of shape (800, 3) instead.

'''

' \n# updated_xtrain = label_encoder.fit_transform(xtrain)\nValueError: y should be a 1d array, \ngot an array of shape (800, 3) instead.\n\n'

In [124]:
label_encoder.fit_transform(xtrain['color'])     #accepts only 1 col

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2,

In [125]:
# label_encoder.transform(xtest)       
'''y should be a 1d array, 
got an array of shape (200, 3) instead.
'''

'y should be a 1d array, \ngot an array of shape (200, 3) instead.\n'

In [126]:
#new input(unseen data)
new_input=['red','red']         
'''all value present then we will transform the values 
- NOT handle unknown labels(label encoder)'''
label_encoder.transform(new_input)

array([2, 2])

In [127]:
#One hot encoder
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)   #sparse_output=False   directly get array
updated_xtrain=encoder.fit_transform(xtrain)             #create new unique columns  shape (800, 9)  #NOT possible to pass 1 col like color only in fit transform
updated_xtrain


array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [128]:
#One hot encoder 2nd method using 2 array


# from sklearn.preprocessing import OneHotEncoder
# encoder=OneHotEncoder()   #sparse_output=True(default)
# values=encoder.fit_transform(xtrain)             #create new unique columns  shape (800, 9)  #not possible to pass 1col like color only in fit transform
# # toarray()
# values=values.toarray()






In [129]:
xtrain       #800 rows × 3 columns

,color,size,material
29,green,small,wood
535,blue,medium,metal
695,blue,small,wood
557,red,small,plastic
836,green,large,plastic
...,...,...,...
106,red,large,plastic
270,red,small,plastic
860,blue,large,plastic
435,blue,small,plastic


In [130]:
columns=encoder.get_feature_names_out()       # return column names based on aescending order

In [131]:
columns

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

In [132]:
# values

In [133]:
# pd.DataFrame(values,columns=columns).astype(int)

In [134]:
encoder.transform(xtest[['color','size','material']])    #or             encoder.transform(xtest)
# fit transform and transform have same col ,The feature names should match those that were passed during fit


encoder.transform(xtest)  #valid syntax why? x test is 2-D 

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [135]:
# # new_input=[['red'],['large']]   #invalid syntax
# new_input=[['red','large'],['blue','small']]

# encoder.transform(new_input)   
# '''ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.'''


In [136]:
# new_input=[['red','large','plastic'],['blue','smaller','wood']]   
'''ValueError: Found unknown categories ['smaller'] 
in column 1 during transform
'''
encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')          #default unknown value -- error
new_input=[['red','large','plastic'],['blue','smaller112','wood']]      #ignore is used to ignore unknown values (assigns-> 0., 0., 0.)
encoder.fit_transform(xtrain)
encoder.transform(new_input)   

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [137]:
col=encoder.get_feature_names_out()

In [138]:
updated_xtrain

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [139]:
pd.DataFrame(updated_xtrain,columns=col).astype(int)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0,1,0,0,0,1,0,0,1
1,1,0,0,0,1,0,1,0,0
2,1,0,0,0,0,1,0,0,1
3,0,0,1,0,0,1,0,1,0
4,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
795,0,0,1,1,0,0,0,1,0
796,0,0,1,0,0,1,0,1,0
797,1,0,0,1,0,0,0,1,0
798,1,0,0,0,0,1,0,1,0


# Ordinal Encoder

In [140]:
from sklearn.preprocessing import OrdinalEncoder

In [141]:
encoder=OrdinalEncoder()

updated_xtrain=encoder.fit_transform(xtrain[['color']])          #should be 2-D(OrdinalEncoder)
'''
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead
'''
# updated_xtrain=encoder.fit_transform(xtrain)
updated_xtrain


array([[1.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [142]:
col=encoder.get_feature_names_out()
col

array(['color'], dtype=object)

In [143]:
pd.DataFrame(updated_xtrain,columns=col).astype(int)

,color
0,1
1,0
2,0
3,2
4,1
...,...
795,2
796,2
797,0
798,0


In [144]:
# updated_xtest=encoder.transform(xtest['color'])   #should be 2-D(OrdinalEncoder)
'''
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead
'''
# updated_xtest=encoder.transform(xtest[['color', 'size'],[ 'material123', 'material']])    
#error not handle unknown values

updated_xtest=encoder.transform(xtest)
updated_xtest


ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- material
- size


In [145]:
# encoder=OrdinalEncoder(handle_unknown='error')---->default
encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

updated_xtrain=encoder.fit_transform(xtrain)
updated_xtest=encoder.transform(xtest)
 
# new_data=[['white','small','wood'],['red','small','wood']]       #uknown value replacing with -1(white is not there)
new_data=pd.DataFrame(data=[['white','small','wood'],['red','small','wood']],columns=['color','size','material'])    
'''
 UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(
'''

updated_new_data=encoder.transform(new_data)
updated_new_data


array([[-1.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [147]:
# encoder=OrdinalEncoder(categories=[['blue','green','red']],handle_unknown='use_encoded_value',unknown_value=-1)
# encoder.fit_transform(xtrain)


'''ValueError: Shape mismatch: 
if categories is an array,
 it has to be of shape (n_features,).

why?xtrain having 3 cols and categories =[[col_ordre]]
when x train columns ==col_orders are same then only transform values
'''

'ValueError: Shape mismatch: \nif categories is an array,\n it has to be of shape (n_features,).\n\nwhy?xtrain having 3 cols and categories =[[col_ordre]]\nwhen x train columns ==col_orders are same then only transform values\n'

In [151]:
encoder.fit_transform([['color'],['size'],['material']])

array([[-1.],
       [-1.],
       [-1.]])

In [157]:
encoder=OrdinalEncoder(categories=[['blue','green','red'],['small','medium','large'],['wood123','metal','plastic']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)






# encoder.fit_transform(xtrain[['color'],['size']])
'''only 2 col i have mentiond in xtrain so ERROR'''



'only 2 col i have mentiond in xtrain so ERROR'

In [162]:
# encoder=OrdinalEncoder(categories=[['small','medium','large'],['blue','green','red'],['wood123','metal','plastic']])
'''ValueError: Found unknown categories ['red', 'blue', 'green'] 
in column 0 during fit'''


# encoder=OrdinalEncoder(categories=[['small','medium','large'],['blue','green','red'],['wood123','metal','plastic']],handle_unknown='use_encoded_value')
'''TypeError: unknown_value should be an integer or np.nan
 when handle_unknown is 'use_encoded_value', got None.'''


encoder=OrdinalEncoder(categories=[['small','medium','large'],['blue','green','red'],['wood123','metal','plastic']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)
encoder.transform(xtest)


array([[-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  2.],
       [-1., -1.,  1.],
       [-1., -1.,  2.],
       [-1., -1.,  2.],
       [-1., -1.,  2.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  2.],
       [-1., -1., -1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1., -1.],
       [-1., -1.,  2.],
       [-1., -1., -1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  2.],
       [-1., -1.,  2.],
       [-1., -1.,  2.],
       [-1., -1., -1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  2.],
       [-1., -1.,  1.],
       [-1., -1., -1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1.,  2.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1., -1.],
       [-1., -1.

***TARGET ENCODER***

In [173]:
from category_encoders import TargetEncoder

encoder=TargetEncoder(cols=['color'],handle_unknown='value')     #target-avg of y train(handle unknown)
'''only color target encoder is applying
 not remove other col'''

# encoder=TargetEncoder(cols=['color'],['size'])


encoder.fit_transform(xtrain, ytrain)   #more unique values then target encoder
encoder.transform(xtest)

,color,size,material
521,263.678700,small,metal
737,263.678700,small,metal
740,256.408397,small,metal
660,253.164751,small,plastic
411,256.408397,medium,metal
...,...,...,...
408,253.164751,small,metal
332,263.678700,large,metal
208,263.678700,small,metal
613,253.164751,small,plastic


In [ ]:
# obj_cols=[]#not a valid

obj_cols=xtrain.select_dtypes(include='object').columns
obj_cols=xtrain.select_dtypes(include='number').columns
encoder=TargetEncoder(obj_cols)

In [178]:
'''new_input=[['red','small','wood1']]
encoder.transform(new_input)

KeyError: 'color'  bcoz i mentioned color column in Target Encoder
'''

new_data=pd.DataFrame({
    'color':['red'],'size':['small'],'material':['wood']
    }) 
encoder.transform(new_data)

,color,size,material
0,263.6787,small,wood


In [179]:
ytrain

29      30
535    219
695    244
557    349
836    233
      ... 
106     66
270    443
860    392
435    318
102     14
Name: price, Length: 800, dtype: int32

In [180]:
df

,color,size,material,price
0,green,large,metal,423
1,red,large,plastic,351
2,green,large,plastic,229
3,green,large,wood,400
4,red,small,plastic,172
...,...,...,...,...
995,blue,small,wood,286
996,blue,large,plastic,473
997,green,medium,plastic,213
998,green,large,metal,203
